config/routes.rb
PainClinic::Application.routes.draw do

  devise_for :users
  resources :patients, :has_many => :intakes

  get "doctors_dashboard/index"
  get "doctors_dashboard/new"
  get "doctors_dashboard/create"
  scope :path=>"patient_reports", :controller=>"patient_reports" do
    get "patient_reports/index"
  end
  scope :path=>'intakes', :controller=>'intakes' do
    post 'search'
  end

  resources :intakes
  get "dashboard/index"
  root :to=>"users#dashboard"
  scope :path=>'users', :controller=>'users' do
    get 'home'
    get 'logout'
    post 'login'
  end

  resources :users
  resources :user_permissions
  post "user_permissions/new"

  mount Blog::Engine, at: "/blog"

  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  	@user = current_user
		@user_permission = @user.user_permission.description
  end

  def completed_tasks
  	render json: Patient.group_by_day(:created_at)
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div style='width:800px'>
<h1 class ='center letters'>Select Workstation  <div class="right image"><%= image_tag 'medical_logo.jpg' %></div></h1>
  <div class="btn-group btn-group-vertical" style="float:left">
	  <ul>
		  <li><%= link_to 'Intake', intakes_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		  <li><%= link_to 'Patient', new_patient_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		  <li><%= link_to 'Doctor', doctors_dashboard_index_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		  <li><%= link_to 'Reports', patient_reports_index_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		<% if @user_permission == 'use blog' %>
		  <li><%= link_to 'Blog', blog.posts_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		<% end %>
		  <li><%= link_to 'Permissions', user_permissions_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		  <li><%= link_to 'Spare', intakes_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %></li>
		</ul>
  </div>
<div><%= image_tag('office.jpg', :style=>'margin: 20px 20px 20px 20px') %></div>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class="image" style="foat:left">
	<%= pie_chart({"Medical Supplies"=>25, "Office Supplies" =>13, "Computer Supplies"=>12, "Labor"=>25, "Lunch"=>25})  %>
</div>

</div>