config/routes.rb
PainClinic::Application.routes.draw do

  devise_for :users
  resources :patients, :has_many => :intakes

  get "doctors_dashboard/index"
  get "doctors_dashboard/new"
  get "doctors_dashboard/create"
  scope :path=>"patient_reports", :controller=>"patient_reports" do
    get "patient_reports/index"
  end
  scope :path=>'intakes', :controller=>'intakes' do
    post 'search'
  end

  resources :intakes
  get "dashboard/index"
  root :to=>"users#dashboard"
  scope :path=>'users', :controller=>'users' do
    get 'home'
    get 'logout'
    post 'login'
  end

  resources :users
  resources :user_permissions
  post "user_permissions/new"

  mount Blog::Engine, at: "/blog"

  

end

app/models/user_permission.rb
class UserPermission < ActiveRecord::Base
		belongs_to :user
end

app/controllers/user_permissions_controller.rb
class UserPermissionsController < ApplicationController
  before_action :set_user_permission, only: [:show, :edit, :update, :destroy]

  # GET /user_permissions
  # GET /user_permissions.json
  def index
    @user_permissions = UserPermission.all.order(user_id: :asc)

  end

  # GET /user_permissions/1
  # GET /user_permissions/1.json
  def show
  end

  # GET /user_permissions/new
  def new
    @user_permission = UserPermission.new
  end

  # GET /user_permissions/1/edit
  def edit
  end

  # POST /user_permissions
  # POST /user_permissions.json
  def create
    @user_permission = UserPermission.new(user_permission_params)
    @user_permission.user_id = current_user.id
    respond_to do |format|
      if @user_permission.save
        format.html { redirect_to @user_permission, notice: 'User permission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_permission }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_permissions/1
  # PATCH/PUT /user_permissions/1.json
  def update
    respond_to do |format|
      if @user_permission.update(user_permission_params)
        format.html { redirect_to @user_permission, notice: 'User permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_permissions/1
  # DELETE /user_permissions/1.json
  def destroy
    @user_permission.destroy
    respond_to do |format|
      format.html { redirect_to user_permissions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_permission
      @user_permission = UserPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_permission_params
      params.require(:user_permission).permit(:description, :user_id)
    end
end

app/helpers/user_permissions_helper.rb
module UserPermissionsHelper
end

app/views/user_permissions/_form.html.erb
<%= form_for(@user_permission) do |f| %>
  <% if @user_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_permission.errors.count, "error") %> prohibited this user_permission from being saved:</h2>

      <ul>
      <% @user_permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Permission, :style=>"color:#BDB76B; font-weight: bold;" %>
    <%= f.text_field :description %>
  </div><br>
  <% hidden_field_tag :user_id %>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary active', :style => 'width: 100px; height: 30px;' %> |
    <%= link_to 'Show', @user_permission, :class => 'btn btn-primary active', :style => 'width: 80px;' %> |
    <%= link_to 'Back', user_permissions_path, :class => 'btn btn-primary active', :style => 'width: 80px;' %><br><br>
  </div>
<% end %>

app/views/user_permissions/edit.html.erb
<h1 class="letters">Editing User Permissions</h1>

<%= render 'form' %>

app/views/user_permissions/index.html.erb
<h1 class="letters">User Permissions</h1>

<table>
  <thead>
    <tr>
      <th style="text-decoration:underline; text-align:left; color:#BDB76B;">User</th>
      <th style="text-decoration:underline; text-align:left; color:#BDB76B;">Permission</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_permissions.each do |user_permission| %>
      <tr>
        <td style="padding-right:40px;"><%= user_permission.user %></td>
        <td style="padding-right:40px;"><%= user_permission.description %></td>
        <td><%= link_to 'Show', user_permission, :class => 'btn btn-mini active' %></td>
        <td><%= link_to 'Edit', edit_user_permission_path(user_permission), :class => 'btn btn-mini active' %></td>
        <td><%= link_to 'Destroy', user_permission,:class => 'btn btn-mini btn-danger active', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>

<%= link_to 'New User permission', new_user_permission_path, :class => 'btn btn-primary active' %> |
<%= link_to 'Back', dashboard_index_path, :class => 'btn btn-primary active', :style => 'width: 120px;'  %>
<br>
<br>

app/views/user_permissions/new.html.erb
<h1 class="letters">New User Permission</h1>

<%= render 'form' %>

app/views/user_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="letters">Permission</h1>

<p>
  <strong>Permission:</strong>
  <%= @user_permission.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_permission.user %>
</p><br>

<%= link_to 'Edit', edit_user_permission_path(@user_permission), :class => 'btn btn-primary active' %> |
<%= link_to 'Back', user_permissions_path, :class => 'btn btn-primary active' %><br><br>