config/routes.rb
PainClinic::Application.routes.draw do

  devise_for :users
  resources :patients, :has_many => :intakes

  get "doctors_dashboard/index"
  get "doctors_dashboard/new"
  get "doctors_dashboard/create"
  scope :path=>"patient_reports", :controller=>"patient_reports" do
    get "patient_reports/index"
  end
  scope :path=>'intakes', :controller=>'intakes' do
    post 'search'
  end

  resources :intakes
  get "dashboard/index"
  root :to=>"users#dashboard"
  scope :path=>'users', :controller=>'users' do
    get 'home'
    get 'logout'
    post 'login'
  end

  resources :users
  resources :user_permissions
  post "user_permissions/new"

  mount Blog::Engine, at: "/blog"

  

end

app/models/intake.rb
class Intake < ActiveRecord::Base
  has_many :intakes_pain_qualities
  has_many :pain_qualities, :through=>:intakes_pain_qualities
  belongs_to :patient

  validates_presence_of :complaint_1 

  def create_pain_qualities(params)
    ids = []
    params.each do |k,v|
      if k.include? "Pain_quality"
        self.pain_qualities << PainQuality.find(k.split("Pain_quality_")[1].to_i)
      end
    end
  end

end

app/controllers/intakes_controller.rb
class IntakesController < ApplicationController
  before_action :set_intake, only: [:show, :edit, :update, :destroy]
  
  def search
    patients = Patient.search(params[:ssn], params[:last_name])
    respond_to do |format|
      format.js{ render :js=>"load_patient_matches(#{patients.to_json})" }
    end
  end
  
  def index
    @intakes = Intake.all
  end

  def show

  end


  def new
    @patient = Patient.find(params[:patient_id])
    @intake = Intake.new
    

  end


  def edit
  end


  def create
    @intake = Intake.new(intake_params)
    @intake.create_pain_qualities(params)
    @intake.patient_id = params[:intake][:patient_id]
    p "XXXXXXXXXXXXXXXXXX"
    p @intake.patient.update_attributes(status_id: 1)
    #@patient = Patient.find(params[:patient_id])
    #@patient.update_attributes(:status_id => 4)
    
    respond_to do |format|
      if @intake.save
        format.html { redirect_to @intake, notice: 'Intake was successfully created.' }
        format.json { render action: 'show', status: :created, location: @intake }
      else
        format.html { render action: 'new' }
        format.json { render json: @intake.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @intake.update(intake_params)
        format.html { redirect_to @intake, notice: 'Intake was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @intake.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @intake.destroy
    respond_to do |format|
      format.html { redirect_to intakes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_intake
      @intake = Intake.find(params[:id])
    end

    def intake_params
      params.require(:intake).permit(:complaint_1, :complaint_2, :complaint_3, :illness_history, :pain_now, :least_pain_one_week, :worst_pain_one_week, :average_pain_last_week, :pain_duration, :pain_timing, :context_of_pain, :modifying_factors, :signs_and_sympotoms, :general_activity, :mood, :normal_work, :sleep, :enjoyment, :concentration, :interaction_with_others, :current_pain_meds, :patient_id)
    end
end

app/helpers/intakes_helper.rb
module IntakesHelper

  def pain_quality_boxes
    PainQuality.all.collect{|pq| ("<tr><td>#{pq.description}</td><td>#{check_box_tag "Pain_quality_"+pq.id.to_s, false, false, :class=>'right'}</td></tr>")}.join
  end

  def pain_quality_list(intake)
    intake.pain_qualities.collect{|pq| ("#{pq.description}<br />")}.join
  end

end

app/views/intakes/_form.html.erb
<h3></h3><br>
<%= form_for(@intake) do |f| %>
  <% if @intake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intake.errors.count, "error") %> prohibited this intake from being saved:</h2>

      <ul>
      <% @intake.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style='width:1200px margin-top:100px' class="field">
    <ul>
      <li><label>Complaint 1:</label><%= f.text_field :complaint_1, :id=>"color" %></li>
      <li><label>Complaint 2:</label><%= f.text_field :complaint_2 %></li>
      <li><label>Complaint 3:</label><%= f.text_field :complaint_3 %></li>
      <li><label>Illness History:</label><%= f.text_field :illness_history %></li>
    </ul>
  </div>
  <br />
  <div class="field" style='margin-top:100px'>
    <table id='pain'>
      <tbody>
        <%= raw pain_quality_boxes %>
      </tbody>
    </table>
  </div>
  <hr class="hr">
  <div style='margin-bottom:150px' class="field">
    <ul>
      <li class='left'><label>Pain Now:</label><%= f.number_field :pain_now %></li>
      <li class='left'><label>Least Pain One Week:</label><%= f.number_field :least_pain_one_week %></li>
      <li class='left'><label>Worst Pain One Week:</label><%= f.number_field :worst_pain_one_week %></li>
      <li class='left'><label>Average Pain Last Week:</label><%= f.number_field :average_pain_last_week %></li>
    </ul>
  </div>
  <hr class="hr">
  <div class="field" style="margin-bottom:150px">
    <ul>
      <li class='left'><label>Pain Duration:</label><%= f.text_field :pain_duration %></li>
      <li class='left'><label>Pain Timing:</label><%= f.text_field :pain_timing %></li>
      <li class='left'><label>Context of Pain:</label><%= f.text_field :context_of_pain %></li>
      <li class='left'><label>Modifying Factors:</label><%= f.text_field :modifying_factors %></li>
    </ul>
  </div>
  <hr class="hr">
  <div class="field margin-line " style="margin-bottom:150px">
    <ul>
      <li class='left'><label>Signs and Symptoms:</label><%= f.text_field :signs_and_sympotoms %></li>
      <li class='left'><label>General Activity:</label><%= f.number_field :general_activity %></li>
      <li class='left'><label>Mood:</label><%= f.number_field :mood %></li>
      <li class='left'><label>Normal Work:</label><%= f.number_field :normal_work %></li>
    </ul>
  </div>
  <hr class="hr">
  <div class="field" style='margin-bottom:150px'>
    <ul>
      <li class='left'><label>Sleep:</label><%= f.number_field :sleep %></li>
      <li class='left'><label>Enjoyment:</label><%= f.number_field :enjoyment %></li>
      <li class='left'><label>concentration:</label><%= f.number_field :concentration %></li>
    </ul>
  </div>
  <hr class="hr">
  <div class="field" style='margin-bottom:150px'>
    <ul>
      <li class='left'><label>current pain meds:</label><%= f.text_field :current_pain_meds %></li>
      <li class='left'><label>interaction with others:</label><%= f.number_field :interaction_with_others %></li>
    </ul>
  </div>
    <%= f.hidden_field :patient_id, :value=>params[:patient_id] %>
  <div class="actions" style="margin-left:30px;">
    <%= f.submit 'Submit', :class => 'btn btn-primary active', :style => 'width: 120px; height:30px;'%>
    <%= link_to 'Back', intakes_path, :class => 'btn btn-primary active', :style => 'width: 120px;'  %>
  </div>
<% end %>

app/views/intakes/edit.html.erb
<h1 class="letters">Editing intake</h1>

<%= render 'form' %>

<%= link_to 'Show', @intake, :class => 'btn btn-primary', :style => 'width: 120px;'  %> |
<%= link_to 'Back', intakes_path, :class => 'btn btn-primary', :style => 'width: 120px;'  %>

app/views/intakes/index.html.erb
<h3 class="letters">Search for a patient or create a new patient</h3><br>
<%= form_tag search_path, :remote=>true do %>
  <span style="color:#BDB76B;"><label><b>SSN:</b></label></span><%= text_field_tag :ssn %>
  <br><b>OR</b><br>
  <br />
  <span style="color:#BDB76B;"><label><b>Last Name:</b></label></span><%= text_field_tag :last_name %>
  <br />
  <%= submit_tag 'search', :class => 'btn btn-primary active', :style => 'width: 120px; height:30px;' %>
  <%= link_to 'New Patient', new_patient_path, :class => 'btn btn-primary active' %>
	<%= link_to 'Back', dashboard_index_path, :class => 'btn btn-primary active', :style => 'width: 120px;'  %>
<% end %>
<div id='results' style="color:green"></div>

app/views/intakes/new.html.erb
<div class="left image" style="margin-right:10px"><%= image_tag 'medical_logo.jpg' %></div><br>
<h1 class="letters">New intake - <%= @patient.to_s %></h1>

<%= render 'form' %>

app/views/intakes/show.html.erb
<p id="notice"><%= notice %></p>

<div style='height:465px; margin:auto; padding:20px; width:100%;'>
<div style="width: 40%; height:475px; float:left;"> 

<p>
  <strong>Complaint 1:</strong>
  <%= @intake.complaint_1 %>
</p>

<p>
  <strong>Complaint 2:</strong>
  <%= @intake.complaint_2 %>
</p>

<p>
  <strong>Complaint 3:</strong>
  <%= @intake.complaint_3 %>
</p>

<p>
  <strong>Illness history:</strong>
  <%= @intake.illness_history %>
</p>
<p>
  <strong>Pain Quality:</strong><br />
  <%= raw pain_quality_list(@intake) %>
</p>

<p>
  <strong>Pain now:</strong>
  <%= @intake.pain_now %>
</p>

<p>
  <strong>Least pain one week:</strong>
  <%= @intake.least_pain_one_week %>
</p>

<p>
  <strong>Worst pain one week:</strong>
  <%= @intake.worst_pain_one_week %>
</p>

<p>
  <strong>Average pain last week:</strong>
  <%= @intake.average_pain_last_week %>
</p>

<p>
  <strong>Pain duration:</strong>
  <%= @intake.pain_duration %>
</p>

<p>
  <strong>Pain timing:</strong>
  <%= @intake.pain_timing %>
</p>

<p>
  <strong>Context of pain:</strong>
  <%= @intake.context_of_pain %>
</p>

</div>
<div style="height:465px; margin-left: 15%;">
<p>

  <strong>Modifying factors:</strong>
  <%= @intake.modifying_factors %>
</p>

<p>
  <strong>Signs and sympotoms:</strong>
  <%= @intake.signs_and_sympotoms %>
</p>

<p>
  <strong>General activity:</strong>
  <%= @intake.general_activity %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @intake.mood %>
</p>

<p>
  <strong>Normal work:</strong>
  <%= @intake.normal_work %>
</p>

<p>
  <strong>Sleep:</strong>
  <%= @intake.sleep %>
</p>

<p>
  <strong>Enjoyment:</strong>
  <%= @intake.enjoyment %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @intake.concentration %>
</p>

<p>
  <strong>Interaction with others:</strong>
  <%= @intake.interaction_with_others %>
</p>

<p>
  <strong>Current pain meds:</strong>
  <%= @intake.current_pain_meds %>
</p>
</div>
</div>
<%= link_to 'Back/Edit', edit_intake_path(@intake), :class => 'btn btn-primary active', :style => 'width: 120px;' %> |
<%= link_to 'Dashboard', dashboard_index_path, :class => 'btn btn-primary active', :style => 'width: 120px;'  %> |
<%= link_to 'New Intake', intakes_path, :class => 'btn btn-primary active', :style => 'width: 120px;' %>